image: python:3.10

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .venv
    - poetry.lock

stages:
  - test
  - format
  - typecheck
  - pages

before_script:
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install -vv

test:
  stage: test
  needs: []
  script:
    - poetry run pytest --junit-xml pytest_report.xml
  artifacts:
    when: always
    reports:
      junit: pytest_report.xml

format:
  stage: format
  needs: []
  script:
    - poetry run black .

type-check:
  stage: typecheck
  needs: []
  script:
    - poetry run mypy --junit-xml mypy_report.xml .
  artifacts:
    when: always
    reports:
      junit: mypy_report.xml

pages:
  stage: pages
  needs: []
  script:
    - poetry run pdoc --html --output-dir build pubnet
    - mv build/pubnet public
  artifacts:
    when: always
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH